from utils.Preprocess import Preprocess
from models.ner.NerModel import NerModel

p = Preprocess(word2index_dic='../train_tools/dict/chatbot_dict.bin',
               userdic='../utils/user_dic.txt')

ner = NerModel(model_name='../models/ner/ner_train.h5', proprocess=p)
hos = '고려병원'; city = '김포시'; s_c = '장기동'
query = ['김포시 장기동 한방과 알려줘']

# query.append(hos + ' 정보!')
# query.append(hos + '과 관련된 정보가 궁금해')
# query.append(hos + ' 진료과목 알려주세요!')
# query.append(hos + '에 대한 진료과목!')
# query.append(hos + ' 진료!')
# query.append(hos + ' 진찰과목 알려줘라')
# query.append(hos + ' 진찰')
# query.append(hos + '에 대한 전문과목 알려주세요')
# query.append(hos + ' 전문')
# query.append(hos + ' 종목알려줘')
# query.append(hos + ' 위치!')
# query.append(hos + ' 주소 알려주세요')
# query.append(hos + ' 네비게이션')
# query.append(hos + ' 가는 길')
# query.append(hos + ' 길찾기')
# query.append(hos + ' 찾아가기')
# query.append(hos + ' 지도!')
# query.append(hos + ' 전화번호 알려주세요')
# query.append(hos + '번호가 궁금해요')
# query.append(hos + ' 연락방법 알려줘')
# query.append(hos + ' 연락처 궁금하네요')
# #########################################
# query.append(city + ' 병원 리스트')
# query.append(city + '에 있는 병원정보 알려주세요')
# query.append(city + ' 주변 병원 정보')
# query.append(city[:-1] + ' 병원 리스트')
# query.append(city[:-1] + '에 있는 병원정보 알려주세요')
# query.append(city[:-1] + ' 주변 병원 정보')
# query.append(city + ' ' + s_c + ' 병원 정보')
# query.append(city + ' ' + s_c + ' 주변 병원')
# query.append(city + ' ' + s_c + ' 병원 리스트')
# query.append(city[:-1] + ' ' + s_c + ' 병원 정보')
# query.append(city[:-1] + ' ' + s_c + ' 주변 병원')
# query.append(city[:-1] + ' ' + s_c + ' 병원 리스트')
# query.append(city + ' 한방병원 리스트')
# query.append(city + ' 종합병원 리스트')
# query.append(city + ' 요양병원 목록 알려줘라')
# query.append(city[:-1] + ' 한방병원 리스트')
# query.append(city[:-1] + ' 종합병원 리스트')
# query.append(city[:-1] + ' 요양병원 목록 알려줘라')
# query.append(city + ' 안과 찾아줘')
# query.append(city + ' 산부인과 병원 리스트')
# query.append(city + ' 피부과 알려주세요!')
# query.append(city[:-1] + ' 안과 찾아줘')
# query.append(city[:-1] + ' 산부인과 병원 리스트')
# query.append(city[:-1] + ' 피부과 알려주세요!')
# query.append(city + '에 있는 피부과 리스트')
# query.append(city[:-1] + '에 있는 피부과 리스트')
# query.append(city + ' ' + s_c + ' 요양병원 리스트 알려주세요')
# query.append(city + ' ' + s_c + ' 피부과 리스트')
# query.append(city + ' ' + s_c + ' 고려병원')

for item in query :
    predicts = ner.predict(item)
    tags = ner.predict_tags(item)
    print(item)
    print(predicts)
    print(tags)
    print('\n')
